# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9e99bcfc179050cd6f16943768d42295db1745ef82f31cf1f2e70190f35435c075abacd6659bc13c170a3493483dd05859b6cb4c8346ef5281a2859e012699e

test:
  secret_key_base: e7dfd0d6d9f4388f1177ac57c5f5e28dfa774376be58f445ec0737f5d7491bfa2e99b0ed13d342acb911ed0354c8690785545552a9193d90a65f54e3a92c81c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
